name: "🐞 버그 리포트"
description: 버그를 보고할 때 사용하는 템플릿입니다.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: bugDescription
    attributes:
      label: 📌 버그 설명
      description: 발생한 문제를 간단하고 명확하게 설명해주세요.
      placeholder: "예: 로그인 버튼을 눌러도 아무 반응이 없습니다."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔁 재현 방법
      description: 버그가 발생하는 과정을 단계별로 작성해주세요.
      placeholder: "1. 로그인 페이지로 이동\n2. 이메일과 비밀번호 입력\n3. 로그인 버튼 클릭\n4. 아무런 반응 없음"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ 기대한 동작
      description: 정상 동작이라면 어떻게 되었어야 하는지 작성해주세요.
      placeholder: "예: 로그인 후 마이페이지로 이동해야 합니다."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ 환경 정보 및 경로
      description: 어떤 환경에서 문제가 발생했는지 작성해주세요.
      placeholder: "예:\n- 경로: https://handa-plan.vercel.app/\n- 브라우저: Chrome 115\n- OS: macOS Ventura 13.4\n- 기기: 데스크탑"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 📸 추가 자료 (스크린샷/콘솔 에러 등)
      description: 스크린샷, 콘솔 로그, 에러 메시지 등이 있다면 여기에 첨부해주세요.
    validations:
      required: false

  - type: input
    id: parentKey
    attributes:
      label: 🔗 Jira Parent Key
      description: 연결할 Jira 부모 이슈 키를 입력해주세요. (예: DIAR-101)
      placeholder: "예: DIAR-101"
    validations:
      required: true
