name: "✨ 기능 구현"
description: 새로운 기능을 추가할 때 사용하는 템플릿입니다.
title: "[Feature]: "
labels: ["feature"]

body:
  - type: input
    id: title
    attributes:
      label: 📌 제목
      description: 어떤 기능을 추가하고 싶은지 명확하게 설명해주세요.
      placeholder: "예: 사용자가 마이페이지에서 프로필 사진을 수정할 수 있는 기능"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 💡 설명
      description: 해당 기능이 왜 필요한지 구체적으로 작성해주세요.
      placeholder: "예: 사용자 맞춤화 및 사용자 경험 개선"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: ✅ 세부사항
      description: 구현해야 할 목록을 작성해주세요.
      placeholder: "- [ ] OO 컴포넌트 구현 1\n- [ ] OO 컴포넌트 구현 2\n- [ ] OO 컴포넌트 구현 3"
    validations:
      required: true

  - type: input
    id: parentKey
    attributes:
      label: 🔗 Jira Parent Key
      description: 연결할 Jira 부모 이슈 키를 입력해주세요. (예: DIAR-100)
      placeholder: "예: DIAR-100"
    validations:
      required: true
