name: "🛠️ 수정"
description: 기존 기능이나 버그를 수정할 때 사용하는 템플릿입니다.
title: "[Fix]: "
labels: ["fix"]

body:
  - type: textarea
    id: problem
    attributes:
      label: 📌 문제 설명
      description: 현재 어떤 버그나 잘못된 동작이 발생하고 있는지 설명해주세요.
      placeholder: "예: 로그인 후 페이지는 이동하지만 토큰이 저장되지 않음"
    validations:
      required: true

  - type: textarea
    id: fixPlan
    attributes:
      label: 🛠️ 수정 예정 방식
      description: 어떻게 고칠 계획인지 간단히 설명해주세요.
      placeholder: "- API 응답 값 검증 로직 추가\n- localStorage 저장 위치 확인 및 보완 예정"
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: ✅ 수정 리스트
      description: 정상 동작이라면 어떻게 되었어야 하는지 작성해주세요.
      placeholder: "- [ ] 로그인 후 마이페이지로 이동해야 합니다.\n- [ ] 수정 리스트 1\n- [ ] 수정 리스트 2"
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: 📎 관련 이슈 / 참고 자료
      description: 관련된 이슈나 문서, 스크린샷, 에러 로그 등 참고할 자료가 있다면 첨부해주세요.
      placeholder: "- 관련 버그 리포트: #27\n- 콘솔 에러 로그: ..."
    validations:
      required: false

  - type: input
    id: parentKey
    attributes:
      label: 🔗 Jira Parent Key
      description: 연결할 Jira 부모 이슈 키를 입력해주세요. (예: DIAR-102)
      placeholder: "예: DIAR-102"
    validations:
      required: true
